name: Build
on: workflow_dispatch
env:
  BUILD_URL: "https://github.com/PrimogemStudio/flutter-starrail"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
            cmd: |
              git clone -b 3.24.3 https://github.com/flutter/flutter --depth 1
              $env:Path="$pwd/flutter/bin;$env:Path"
              flutter --version
              git clone $env:BUILD_URL project --depth 1
              cd project
              flutter build windows
              flutter assemble -dTargetPlatform=windows-x64 -dBuildMode=release -dTargetFile="lib/main.dart" --output=build/aot release_bundle_windows-x64_assets
              cp ./build/aot/flutter_assets ../app -r
              cp ./build/aot/windows/app.so ../app/win.so

          - os: ubuntu-latest
            name: Linux
            cmd: |
              sudo apt update -y 
              sudo apt upgrade -y;
              sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
              sudo apt install ninja-build
              sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
              git clone -b 3.24.3 https://github.com/flutter/flutter --depth 1
              export PATH=$(pwd)/flutter/bin:$PATH
              flutter --version
              git clone $BUILD_URL project --depth 1
              cd project
              flutter build linux
              mkdir ../app
              cp build/lib/libapp.so ../app/lin.so

          - os: macos-14
            name: MacOS
            cmd: |
              git clone -b 3.24.3 https://github.com/flutter/flutter --depth 1
              export PATH=$(pwd)/flutter/bin:$PATH
              flutter --version
              git clone $BUILD_URL project --depth 1
              cd project
              flutter build macos

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        if: ${{ matrix.os != 'macos-14' }}
        run: |
          ${{ matrix.cmd }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: ./app
